- swan/Chart.lock
- swan/Chart.yaml
No other changes than using a more recent fusex chart and bumping swan chart at 0.0.5
This is used by ScienceBox and should not interfere with swan-cern.
> Use new fusex@0.1.0 chart

- .gitlab-ci.yml
1. Pushes only the chart whose name matches the tag (e.g., 'swan@0.0.5')
2. Makes sure the version in <chart_name>/Chart.yaml matches the tag version
> Improve CI for building and pushing Helm charts to registry.cern.ch

- swan-cern/swan.dev.values.yaml
- swan/values.yaml
- Update the user image to v5.14.1 containing SparkConnector v2.1.0
- Removes unused cdh jar loaded from EOS for spark.driver.extraClassPath
- JupyterLab support for SparkConnector
- Remove the config from swan.dev.values.yaml (as it is the same as the parent chart)
> Update user image to v5.14.1

- swan-cern/files/private/dev/hadoop_token.sh
- swan-cern/files/private/prod/hadoop_token.sh
- swan-cern/files/swan_spark_config.py
- swan-cern/templates/hadoop-token-generator.yaml
- swan-cern/values.yaml
Make `/cvmfs/sft.cern.ch/lcg/etc/hadoop-confext` path configurable, now that we have `/cvmfs/sft.cern.ch/lcg/etc/hadoop-confext-qa` deployed from the qa branch of https://gitlab.cern.ch/db/hadoop-confext
> Add configuration for hadoop-confext path

- swan/values.yaml
All other configs required to have EOS working with oAuth are set in the eosxd chart (https://gitlab.cern.ch/helm/charts/cern/-/merge_requests/78)
> Show EOS file versions

- swan-cern/values.yaml
- swan/Chart.lock
- swan/Chart.yaml
- swan/values.yaml
The CVMFS daemonSet now comes with prefetching functionality:
- There is a second container running in the daemonSet pod
- The container image is the same used by cvmfs main to avoid the overhead of pulling and storing a second image
- Such container runs crond, whose output goes to stdout (some debug flags are enabled)
- cronjobs are passed as configMap and can be set from values.yaml
Tested in ScienceBox:
```
NAME                                   READY   STATUS                  RESTARTS   AGE
hub-6f6c467cfc-7klmn                   1/1     Running                 0          19m
proxy-7cffc688b8-vmz4h                 1/1     Running                 0          19m
sciencebox-cvmfs-bk2z6                 2/2     Running                 0          19m
[...]
---
[...
c]ontainers:
cvmfs: …
```
> Use cvmfs@0.0.5 with prefetcher functionalities

- swan/files/swan_config.py
A large environment created by many kubernetes service objects causes timeouts in the EOS daemonset looking up the user environment for access tokens etc
> Remove service enviornment variables from user pods

- swan/Chart.lock
- swan/Chart.yaml
This is a dependency update for the fusex chart, i.e., the daemonSet implementation for ScienceBox.
My understanding is that this is not used for swan-cern prod (which instead uses the CSI driver), so nothing should break.
I used `qa` as base branch. Let me know if I should rebased against something else.
> Update fusex chart to 0.1.2

- swan-cern/options_form_config.json
- Add 102swan and 102cuda in recommended releases
- Make gcc 11 the default compiler version for LCG 102
- Move 99 python2 and 101 to other releases
---
Before:
After:
> Add LCG 102 to options form

- swan-cern/files/private/prod/webhdfs_token.sh
As function `get_namenodes` runs in a subshell (in `$()`) we need to explicitly write `NAMENODES` to stdout
> Fix HDFSBrowser missing webhdfs token

- swan-cern/files/swan_spark_config.py
- To allow spark/dask workers to reach the driver running in a user pod from outside the cluster, we open ports using `type: NodePort` services
- We have a limited number of ports available for `type: NodePort` kubernetes services. The available range is specified through the `--service-node-port-range` [flag](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport) (default: 30000-32767) when creating the cluster. This currently only support ~150 users with 18 ports open for each user session/pod.
This change cleans up these services when the spawner stops the user server, to prevent them from accumulating over time.
Related: #64 fixed issues caused by too many environment variables due to many services in the namespace, causing timeouts in EOS daemon trying to …
> Cleanup spark NodePort services

- swan-cern/values.yaml
- Aligns with puppet nodes to create `/etc/condor` from the batch service configuration
- Sets the environment variable to toggle the [flag](https://github.com/swan-cern/systemuser-image/blob/effdb9edb0262ba75ff94e19b914049460dd3e92/systemuser.sh#L216) in the image.
> Enable CERN HTCondor configuration flag

- swan/values.yaml
- Waits for 5 minutes for hub to start up.
- Restarts hub container if probe fails for 20 * 15 = 5 minutes
- I have increased the timeouts from the [upstream defaults](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/5c0d0c5c74bc97bf403844ced6b8e79cc089498d/jupyterhub/values.yaml#L118) (adjusting other values to restart in 5 minutes) to ensure we don't restart the hub unless it is really stuck.
> Enable Liveness Probe for Hub Pod

- swan-cern/files/swan_config_cern.py
Temporary workaround to prevent creating many user sessions on GPU nodes, which seems to trigger an EOS error in v<5. To be removed after the EOS upgrade to v5.
> Do not schedule CPU-only pods on GPU nodes

- swan-cern/files/private/cull_check_ticket.sh
- swan-cern/files/swan_config_cern.py
The size of the kerberos credentials cache is large for some users.
The curl command to replace the secret fails because the arguments are too long. So instead this passes the JSON body as a file
- Also adds a `swan_user: ` label to the secret aligning with the pod labels
> Fix EOS Kerberos Auth failing due to large KRB5CC

- swan-cern/values.yaml
- swan/values.yaml
- Updates the LCG release numbers to the latest that are currently in production.
- Removes warming up of Spark2 stack, since it is not used as much as the other stacks (SWAN, NXCALS, CUDA)
- Configures the swan chart to define the LCG_102swan cron job for the Python kernel, while the swan-cern chart takes care of LCG102_swan for the ROOT kernel, the NXCALS and the CUDA stacks.
- Fixes an issue with the Pytorch package (its name in Python is torch, not pytorch).
- Fuses the import of tensorflow and torch in a single cron job.
- Removes the setting of specific minutes in which the warming up of the CUDA stack happens. Running it every 15 minutes like the rest of the stacks should be good enough.
- Removes the redirection to /dev/null when importing packages, so we can find those errors in …
> Reorganize cron jobs for warming up CVMFS cache

- swan/values.yaml
https://github.com/swan-cern/jupyterhub-image/releases/tag/v1.28
> Upgrade Hub image to v1.28

- swan/files/swan_config.py
- swan/values.yaml
When running on Kubernetes we do not take nodes offline with /etc/nologin, and this mechanism is broken in the Kubernetes setup. Browser pages make a request every 60s to ping for notifications to the hub. Disabling this also reduces the load on the hub pod.
Works together with https://github.com/swan-cern/systemuser-image/pull/93
> Disable request to hub for Maintenance Notifications

- swan-cern/values.yaml
- Always use the timestamp from containerd, instead of parsing the time in the log
- Remove multiline concatenation
- Simplify index names, with two indexes `logs`, `metrics` (passed as data.type) to monit
- Simplify the pipeline by avoiding duplicate filters, and refactor tagging between filters
- Remove parsing log_level, log_source and other unnecessary fields not used from kibana
> Clean Up Fluentd Configuration

- swan-cern/values.yaml
From now on, there will be two producers: swan and swan-qa. Those will be specified in the values.yaml of the prod and qa environments in the GitOps repo, respectively.
> Remove producer from swan-cern chart fluentd configuration

- swan-cern/values.yaml
SSO tokens have an updated validity of 2 hours. This change ensures jupyterhub does not refresh the token when recieving a request for 110 minutes since a previous request
> Update interval that authenticator skips refreshing between refresh_user calls

- swan-cern/files/private/side_container_tokens_perm.sh
- swan-cern/files/swan_config_cern.py
This commit is one of two parts of a fix for refreshing the EOS kerberos ticket in SWAN kubernetes, the other part being some changes in the systemuser image.
The current problem is that the EOS kerberos ticket that is used by the notebooks and terminal processes is never refreshed in k8s, only the ticket that is used by the Jupyter server is refreshed. This commit ensures both are refreshed, although the former can be overwritten by the user via kinit, which makes the user responsible for the ticket renewal from that point on.
> Fix refreshing of EOS kerberos ticket for notebooks and terminals (part 1)

- swan-cern/values.yaml
- swan/files/swan_config.py
Setting a pod affinity based on the LCG release that the user selected leads to pods being clustered in nodes by the kubernetes scheduler. This, together with overcommitting of the nodes, can cause memory pressure in crowded nodes where multiple users use the memory of their sessions up to the limit.
By removing this affinity setting, we seek to rely instead on the default strategy of the k8s scheduler, which tries to assign pods to least allocated nodes. This will make it less likely, unless the cluster is close to full capacity, that one or more users push a node's memory to the limit.
Note that the affinity setting was done to favour warm CVMFS caches in nodes so users had a better experience. However, most of our current users select the default software stack, the NXCALS stack or the …
> Remove user pod affinity based on LCG release

- swan-cern/values.yaml
- swan/values.yaml
Remove options of the eosxd chart that are now specified upstream, namely:
https://gitlab.cern.ch/kubernetes/automation/charts/cern/-/commit/f802519dc1f7625eadc65b7f0b7eb2d59b0986e9
https://gitlab.cern.ch/kubernetes/automation/charts/cern/-/commit/8a97f658dd4221c01ac8cf946394af4c15397738
Those options made it to the eosxd 5.1.5 tag.
> Remove options specified upstream by eosxd chart

- swan-cern/files/swan_config_cern.py
This reverts commit 9aa2152835e668f7f8593ad796b926ecaa032bc6.
Since we are about to update to EOS v5, it is time to remove the limitation of GPU nodes not being able to schedule regular user sessions. This limitation was put in place because EOS v4 errors were more likely (and affected more people) in crowded GPU nodes.
> Revert "Do not schedule CPU-only pods on GPU nodes"

- swan-cern/values.yaml
This PR proposes a few changes in the resource specification of user, eosxd and cvmfs pods to:
- User pods: make the memory resource request dynamic, more precisely a fraction of the limit.
- eosxd and cvmfs: set a baseline memory request so that the k8s scheduler is aware from the start that such pods have some memory consumption.
> Change resource settings for user pods, eosxd and cvmfs

- swan/values.yaml
Contains changes in SwanSpawner to make the setting of the user pod memory request dynamic.
> Update Jupyterhub image to 1.30

- swan/Chart.lock
- swan/Chart.yaml
- swan/values.yaml
New features:
- Possibility to specify configuration globally or per mount: used for `hide-versions:0`.
- New mounts: opendata and hepdata
> Update eosxd chart dependency to 5.1.5-2 tag

- swan/files/swan_config.py
In order to run OpenCL programs on an NVIDIA GPU platform, OpenCL needs to be configured to use the NVIDIA vendor ICD (Installable Client Driver), i.e. the libnvidia-opencl library. The latter provides the OpenCL implementation that is specific for NVIDIA GPU architectures.
Such configuration can be achieved with the OCL_ICD_FILENAMES environment variable. More information here:
https://github.com/KhronosGroup/OpenCL-ICD-Loader
This is needed for the inverted CSC, in particular for an exercise session where `pyopencl` will be used.
For reference, SPI ticket with discussion about this topic:
https://sft.its.cern.ch/jira/browse/SPI-2300
> Configure OpenCL to use NVIDIA backend

- .github/workflows/release-charts.yaml
- .github/workflows/tag-chart.yaml
- swan-cern/Chart.lock
- swan-cern/Chart.yaml
This includes:
- Changing the dependencies in our charts that are already published as OCI repository
- Change our CI/CD that tags our charts to use OCI instead of chartmuseum
> Adapt to OCI format

- swan/values.yaml
Keycloak is going to be updated at CERN and without this scope calls to userinfo endpoint will fail.
AFAIK nothing on our code calls this endpoint, except the EOS server that uses it to verify the validity of the token we send. But, since we still use krb in production, I don't expect anything to break, but...
I've made the same change in puppet qa, needs to be merged to prod and jupyterhubs restarted. But since this should not affect anyone, I leave that for your consideration.
[OTG0076533](https://cern.service-now.com/service-portal?id=outage&n=OTG0076533)
> auth: request openid scope for standard compliance

- swan/values.yaml
Contains fix for not taking Python modules placed on SWAN_HOME.
> Update systemuser image to v5.18.2

- swan/values.yaml
Has fix for not depending on user-defined labextension.yaml to select SwanHTCondorCluster.
> Update systemuser image to v5.18.3

- swan-cern/values.yaml
This is to claim back resources more quickly, which is becoming especially important in the case of GPUs. It still gives enough time for pauses during the day without losing the session.
> Reduce allowed session inactivity period to 4 hours

- swan-cern/values.yaml
It is becoming common that users fail to start a GPU session because of lack of resources. This will hint them in that direction.
> When session fails to start, mention that all GPUs might be busy

- swan-cern/values.yaml
Fix to pick newer hadoop-fetchdt version.
> Update hadoop token generator image to v2.1.2

- swan-cern/files/swan_spark_config.py
Link to the SNOW form of the Hadoop service.
https://hadoop.web.cern.ch does not exist.
> Fix message when user does not have access to analytix

- swan/values.yaml
In preparation for https://cern.service-now.com/service-portal?id=outage&n=OTG0079117
> Upgrade user image to v5.18.5

- swan-cern/files/swan_config_cern.py
- swan/files/swan_config.py
Remove settings that are no longer necessary in the spawner hooks w.r.t. GPU configuration, or move them to the SwanKubeSpawner if they are still needed.
> Clean GPU-related logic in spawner hooks

- swan/files/swan_config.py
The culler service invokes check_ticket.sh, which invokes eos_token.sh, which makes use of the SWAN_DEV variable to decide on its behaviour.
Without this setting, the culler service does not get such variable from the hub, even when it's set for a dev cluster.
> Propagate SWAN_DEV env variable to culler service

- swan-cern/values.yaml
- swan/values.yaml
Since we are promoting LCG 104a and 104a CUDA as default releases.
> Warm up LCG 104a and 104a CUDA

- swan/values.yaml
Includes fixes in SwanContents for cloning of git repositories.
> Update user image to v5.18.8

- swan/Chart.lock
- swan/Chart.yaml
This version of the chart installs CVMFS v2.11, which contains a fix so that only open FD are closed. This affected SWAN when moving to k8s v1.25, where the containerd installation had a configuration for unlimited FD.
More information:
https://github.com/cvmfs/cvmfs/pull/3182
> Update CVMFS chart to v0.0.8

- swan-cern/values.yaml
Uses alma9 repository for hadoop fetchdt package.
> Update hadoop token generator image to v2.1.3

- swan/values.yaml
Fix for creating centos7 kerberos tickets that are used by an alma9 eosxd.
> Update user image to v5.18.9

- swan/values.yaml
Contains changes to support the new Spark k8s cluster.
To be merged after confirmation that all QA tests are fine.
> Update hub image to v3.4

- swan/values.yaml
With the newly added support for Alma9, two images will coexist (Alma9 and the old CentOS7). Here we configure Alma9 via chart settings and the URL of the CentOS7 image is provided via an option of our kubespawner.
Note: name and tag of the Alma9 image are subject to change before merging this PR.
> Configure new Alma9 image instead of CentOS7 via chart settings

- swan/values.yaml
To release a new tag of the charts that uses the new swan-cern:v0.0.2, on which we are going to work next (Spark, Condor, other fixes).
> Use alma9 user image swan-cern v0.0.2

- swan-cern/files/swan_computing_config.py
- swan-cern/files/swan_spark_config.py
- swan-cern/templates/config.yaml
- swan-cern/values.yaml
This is to implement a special treatment for HTCondor pools at the level of the modifier pod hook.
Now Spark and HTCondor will share a hook, which will configure both. The reason for this is that both share the need to open ports in the user session. Depending on what the user selects in the form (Spark, HTCondor or both) we will create a k8s service that provides the corresponding ports.
> Turn Spark pod hook into a generic hook for handling external computing integrations

- swan/values.yaml
Includes spawner support for HTCondor integration.
> Update JupyterHub image to v3.6

- swan-cern/files/swan_computing_config.py
SPARK_PORTS is consumed by the port allocator version that runs in the systemuser CentOS7 image. We need to keep compatibility with such version for as long as we support the CentOS7 image.
> Keep support for SPARK_PORTS, used in CentOS7 systemuser image

- swan-cern/values.yaml
This value was changed, as the puppet nodes are being taken out of service and so, there will be a higher number of user sessions running in the SWAN kubernetes cluster.
Therefore, taking into account the maximum number of CPUs available, it was decided to allocate half of a CPU per user session, to allow for more user sessions to be scheduled.
> Allocate half of a CPU per user session

- swan/values.yaml
The ingress class annotation is deprecated and so it was replaced.
> Replace ingress class annotation with ingressClassName chart value

- swan-cern/templates/gpu/nvidia-hack-force-mig-config.yaml
Since it needs to access the admin service account in that namespace.
> Move daemonset to kube-system namespace

- swan/values.yaml
Has a new spawner version that implements allocation of event participants in specific resources.
> Update hub image to v3.10

- swan-cern/values.yaml
Not sure if it also needs to be added to the list of repos on line 30 ? But /cvmfs/grid.cern.ch has the certs etc to make voms proxies work on the client side.
> add /cvmfs/grid.cern.ch

- swan/values.yaml
Has support for voms-proxy-init on Alma9.
> Update swan-cern image to v0.0.13

- swan-cern/values.yaml
This change is temporary, as it is not intended to be deployed in the next service intervention.
> swan-cern: Revert addition of grid.cern.ch repository to CVMFS

- .github/workflows/update-images.yaml
This is to prevent errors with the sed command, since the / is also used to indicate the path of the docker image that will have their version replaced.
> ci: Use different separator for sed command

- swan/values.yaml
Contains a fix for JupyterLab UI extensions (matplotlib, ipywidgets).
> Update swan-cern image to v0.0.20

- swan-cern/values.yaml
Contains installation of cronie for cvmfs-csi prefetcher.
> swan-cern: Update user image tag to v.0.0.21

- swan-cern/values.yaml
Since swan-cern is launched with jovyan by default, and we need the prefetcher container to run as root.
> swan-cern: Configure cvmfs prefetcher to have its own image

- swan-cern/values.yaml
- swan/Chart.yaml
- swan/files/swan_config.py
- swan/values.yaml
Use eosxd-csi chart for EOS as the old chart was no longer maintained (fusex). Furthermore, removed unused eos chart that was present in the SWAN chart Chart.yaml file.
This new chart allows to specify custom mountpoints on the nodes of the kubernetes cluster, which was a limitation of the fusex chart, meaning that it is possible to have two different deployments of EOS running in the same kubernetes cluster.
> Change EOS chart used by SWAN

- swan/templates/cvmfs/pvc.yaml
- swan/values.yaml
Deploy it through the cvmfs-csi chart instead of defining it in the swan chart, for simplicity purposes
> Deploy cvmfs storage class through cvmfs-csi chart

- swan/values.yaml
As this setting existed for the old eosxd chart and allows notebook checkpoints to be created and restore to them.
> Enable checkpoints in eosxd-csi for user home and project

- swan-cern/values.yaml
Contains fix for SwanShare and SwanContents in hub v4.1.6
> [swan-cern] Update swan-cern image to v0.0.24

- swan-cern/values.yaml
- swan/values.yaml
This change intends to increase security by only allowing the user pods to communicate with authorized resources, such as the hub and proxy and allow incoming traffic from specific origins, including spark and htcondor.
> Add network policies to restrict traffic in user pods

- .github/workflows/release-charts.yaml
Only fail the pipeline if none of the three charts has changes.
> ci: Trigger chart release if swan-cern-system has changes

- swan-cern-system/values.yaml
It was decided to disable the chart for now, as it requires further investigation on how to use it and the parameters to set regarding resources usage
> swan-cern-system: Disable monitoring chart

- swan/values.yaml
This is already done by the network policies set in place by us.
> fix: Disable blocking the cloud metadata server with iptables

- swan-cern/files/private/side_container_tokens_perm.sh
Since now the side-container uses Alma9 as image, which does not include diff by default.
> [swan-cern] Install diff

- swan-cern/files/private/side_container_tokens_perm.sh
- swan-cern/files/swan_config_cern.py
Since such image will be pulled anyway for its use by the user pod, and it includes already the diffutils package that is required by the script that renews the EOS tickets (no need to install it dynamically anymore).
> [swan-cern] Use notebook container image for sidecar container

- swan-cern/files/swan_config_cern.py
When using the swan-cern user image, by default jovyan is used. This commits forces the use of root.
> [swan-cern] Sidecar container needs to run as root

- swan/values.yaml
This is because dockerhub and other registries impose rate limits when pulling images from their repositories.
> swan: Use harbor cache to pull docker images

- swan-cern-system/values.yaml
This change is due to the existence of rate limits when pulling images from docker.io. By pulling the image from the CERN registry, it will stay cached, without the need to always pull it from docker.io
> swan-cern-system: Pull docker.io image through CERN registry

- swan-cern-system/templates/fluentd/fluentd_filters.conf.yaml
- swan-cern-system/templates/fluentd/fluentd_sources.conf.yaml
- swan-cern-system/values.yaml
- swan-cern/README.md
- swan-cern/templates/falco-custom-rules.yaml
These two rules are made for tracking users activity, including:
- Logging each executed command via jupyter terminal;
- Logging every incoming and outcoming connection established with the user's pod.
The change on grok rules is made for not allowing the filtering rules to ignore falco logs (because falco pods are deployed within the kube-system namespace, which is being currently ignored by the `ignoreInternal` value). So a new value `internalFalco` was created in order to open an exception to this generic rule.
> Custom rules for Falco

- swan-cern/files/swan_computing_config.py
This is following a change of name and paths made by the hadoop team
> swan-cern: Change analytix cluster name to hadoop-analytix

- swan-cern/values.yaml
To adapt to new hadoop-analytix nomenclature.
> swan-cern: Update hadoop token generator to v3.0.5

- swan/values.yaml
Allows to prevent silent re-login after the refresh token expired.
> Remove offline_access scope from KeyCloakAuthenticator

- swan-cern-system/templates/fluentd/fluentd_filters.conf.yaml
- swan-cern-system/templates/fluentd/fluentd_sources.conf.yaml
- swan-cern-system/values.yaml
This change is made for not allowing the filtering rules to ignore falco logs (because falco pods are deployed within the kube-system namespace, which is being currently ignored by the `ignoreInternal` value). So a new value `internalFalco` was created in order to open an exception to this generic rule.
> swan-cern-system: New includeFalco value

- swan-cern-system/templates/fluentd/fluentd_filters.conf.yaml
Add new community tag to differentiate and filter logs coming from different instances of SWAN, such as the general instance and the ATS one while using the production and qa monit producers
> swan-cern-system: Add fluentd tag to differentiate logs

- swan-cern/files/swan_computing_config.py
- swan-cern/files/swan_config_cern.py
- swan-cern/values.yaml
- swan/files/swan_config.py
- swan/values.yaml
Add options to implement new logic in the culler that detects, every 12 hours, which users have been blocked.
> [swan-cern]: add options to implement new logic in the culler for blocked users

- swan-cern/values.yaml
Prometheus will be deployed through the swan-cern-system chart (using the monitoring one as dependency) in the swan-cern-system namespace. Therefore, the policy needs to be updated to allow connections from such namespace
> swan-cern: Change prometheus network policy namespace to swan-cern-system

- swan-cern/files/swan_computing_config.py
- swan/templates/rbac.yaml
The goal is to show to the user only the GPU models that are free. 
- If the user try to create a session while no GPU are available -> an error will be show.
- "watch" permission has been added to pod in the SWAN namespace.
> [swan, swan-cern]: See available gpus flavour (rebase from Enric PR)

- swan-cern-system/templates/prometheus/rules.yaml
Change labels to the new ones exported by the monitoring chart. Furthermore, remove the cern-magnum release label, as Prometheus is no longer deployed through cern-magnum.
Do not merge until the new chart of monitoring is deployed in production.
> swan-cern-system: Change prometheus rules according to new monitoring chart

- swan-cern/values.yaml
add egress rule for port 6443 to fix connectivity with Cilium, cf issue: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/3202
> [swan-cern] fix(networkpolicy): add egress rule for port 6443 
