swan-cern/swan-charts

- swan-cern/options_form_config.json
change names for lcg releases for nxcals
> Optionsform

- swan-cern/Chart.lock
- swan-cern/Chart.yaml
> bump versions

- .github/workflows/release-charts.yaml
- .github/workflows/tag-chart.yaml
- swan-cern/.bumpversion.cfg
- swan/.bumpversion.cfg
Add username to commits created when releasing from CI
example commits: https://github.com/krishnan-r/swan-charts/commits/master
> Include username in CI version bump commit message

- .github/workflows/release-charts.yaml
- .github/workflows/tag-chart.yaml
- swan-cern/.bumpversion.cfg
- swan-cern/files/private/cull_check_ticket.sh
- swan-cern/files/swan_config_cern.py
- swan/.bumpversion.cfg
> Merge QA -> Master

- utils/deploy_k8s.sh
> Merge QA to Master

- swan-cern/values.yaml
- swan/values.yaml
> [QA -> Master] Reorganize cron jobs for warming up CVMFS cache

- swan/values.yaml
> [QA -> Master] Update Hub Image  & Make Notebook Default Container

- swan-cern/options_form_config.json
And move LCG 102 and 102 CUDA further down in the selection menu.
> Set LCG 102b and 102b CUDA as recommended releases

- swan/values.yaml
Includes loading screen for login page
> Update JupyterHub image to v1.26

- swan-cern/values.yaml
- swan/values.yaml
> [QA - Master] Login Loading Screen

- swan-cern/values.yaml
Since we have merged https://gitlab.cern.ch/swan/gitops/-/merge_requests/8.
> Update NXCALS cron job to warm up 102b

- swan-cern/files/swan_config_cern.py
- swan-cern/files/swan_spark_config.py
Deletes the eos and hadoop tokens secret from a hook in the spawner when a server stops.
> Cleanup user secrets when a session stops

- swan-cern/files/private/prod/hadoop_token.sh
- Update LCG release
- Remove sterile code
> Update hadoop token generator script

- swan/values.yaml
Includes bug fix in SwanHelp for SWAN gallery in JupyterLab.
> Update systemuser image to v5.17.2

- swan/values.yaml
Fix for name of culler scripts.
> Update to hub image v2.2

- swan-cern/templates/hadoop-token-generator.yaml
- swan-cern/values.yaml
- swan/values.yaml
And add an environment variable to the hadoop token generator to activate development mode (changes behaviour of hadoop_token.sh).
> Update hub and hadoop token generator images

- swan-cern/files/swan_config_cern.py
- swan-cern/files/swan_spark_config.py
- swan-cern/templates/hadoop-token-generator.yaml
- Pass SWAN_DEV environment to wrappers correctly
- SWAN_DEV flag was incorrectly setup always to false
> Fixes to enable SWAN_DEV flag support

- swan/Chart.lock
- swan/Chart.yaml
After @ebocchi pushed it to harbor.
> Use OCI URL for cvmfs dependency

- swan/values.yaml
Contains use of new EOS keytab.
> Update jupyterhub image to v2.4

- swan-cern/values.yaml
In preparation for https://cern.service-now.com/service-portal?id=outage&n=OTG0079117
> Warm up new 102b NXCALS PRO PyTimber PRO

- swan/values.yaml
Wait for pipelines to finish:
https://gitlab.cern.ch/swan/docker-images/systemuser/-/commit/04990e004775353b75998888b5bcf3afb71db751
https://gitlab.cern.ch/swan/docker-images/jupyterhub/-/commit/b34cd68ba38781a70d1445b47f1c7e302cedb8d1
> Updates for hub and systemuser image

- swan-cern/values.yaml
> Mount CVMFS repository for SHIP experiment

- swan/Chart.lock
- swan/Chart.yaml
> Update to latest eosxd

- swan-cern/values.yaml
> Warm up new LCG 105a NXCALS stack

- swan-cern/files/swan_computing_config.py
- swan/files/swan_config.py
Since the code was initially projected to be dependent on LCG configurations, extra prevention measures need to be taken, since these LCG configurations are no longer present for custom environments.
> Prevention against KeyErrors

- swan/values.yaml
Contains fix for local home in Alma9.
> [swan] Update hub image to v3.20

- swan-cern/Chart.lock
- swan-cern/Chart.yaml
point to registry instead of local charts
> swan-cern: update swan chart

- swan-cern/Chart.lock
- swan-cern/Chart.yaml
- swan-cern/templates/gpu/nvidia-device-plugin-config.yaml
- swan-cern/values.yaml
This new GPU operator version comes with security updates requested by the CERN security team and changes to the values of the `gpu-operator` chart.
> Feature: New GPU operator version v24.6.2

- swan-cern/files/swan_computing_config.py
An events user also needs to:
- Decrease the count of the GPU flavor they take
- Add affinity with nodes of the particular GPU product (e.g. A100 or TeslaT4) they select
> [swan-cern] Apply logic for regular user also to events user
